# Generated by Django 4.0.4 on 2022-06-11 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import galleries.models
import main.common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Hide'), (3, 'Published')], default=3)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'Galleries',
            },
            bases=(models.Model, main.common.CheckAgeMixin),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=300, null=True)),
                ('how_often', models.CharField(choices=[('Once every 2-3 days', 'Once every 2-3 days'), ('Once a week', 'Once a week'), ('Once every 2 weeks', 'Once every 2 weeks')], default='Once a week', max_length=20)),
                ('image', models.ImageField(upload_to=galleries.models.upload_to)),
                ('source', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Hide'), (3, 'Published')], default=3)),
                ('send_reminder', models.BooleanField(default=False, verbose_name='Send reminder to email')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galleries.gallery')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, main.common.CheckAgeMixin),
        ),
    ]
