# Generated by Django 4.0.4 on 2022-08-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hide'), (2, 'Published')], default=2),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hide'), (2, 'Published')], default=2),
        ),
    ]
