# Generated by Django 4.0.4 on 2022-08-30 13:00

from django.db import migrations, models
import galleries.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=galleries.models.upload_to),
        ),
    ]
