# Generated by Django 4.0.4 on 2022-06-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletteruser',
            name='name',
        ),
    ]
