# Generated by Django 4.0.4 on 2022-06-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_newsletteruser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
