# Generated by Django 4.0.4 on 2022-06-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_newsletter_body_alter_newsletter_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.ManyToManyField(default='YOUR_GMAIL', to='main.newsletteruser'),
        ),
    ]
